// Generated by gencpp from file rfans_driver/null.msg
// DO NOT EDIT!


#ifndef RFANS_DRIVER_MESSAGE_NULL_H
#define RFANS_DRIVER_MESSAGE_NULL_H

#include <ros/service_traits.h>


#include <rfans_driver/nullRequest.h>
#include <rfans_driver/nullResponse.h>


namespace rfans_driver
{

struct null
{

typedef nullRequest Request;
typedef nullResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct null
} // namespace rfans_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rfans_driver::null > {
  static const char* value()
  {
    return "0ec340068269569bdcfcbf79cb9781d5";
  }

  static const char* value(const ::rfans_driver::null&) { return value(); }
};

template<>
struct DataType< ::rfans_driver::null > {
  static const char* value()
  {
    return "rfans_driver/null";
  }

  static const char* value(const ::rfans_driver::null&) { return value(); }
};


// service_traits::MD5Sum< ::rfans_driver::nullRequest> should match 
// service_traits::MD5Sum< ::rfans_driver::null > 
template<>
struct MD5Sum< ::rfans_driver::nullRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rfans_driver::null >::value();
  }
  static const char* value(const ::rfans_driver::nullRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rfans_driver::nullRequest> should match 
// service_traits::DataType< ::rfans_driver::null > 
template<>
struct DataType< ::rfans_driver::nullRequest>
{
  static const char* value()
  {
    return DataType< ::rfans_driver::null >::value();
  }
  static const char* value(const ::rfans_driver::nullRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rfans_driver::nullResponse> should match 
// service_traits::MD5Sum< ::rfans_driver::null > 
template<>
struct MD5Sum< ::rfans_driver::nullResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rfans_driver::null >::value();
  }
  static const char* value(const ::rfans_driver::nullResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rfans_driver::nullResponse> should match 
// service_traits::DataType< ::rfans_driver::null > 
template<>
struct DataType< ::rfans_driver::nullResponse>
{
  static const char* value()
  {
    return DataType< ::rfans_driver::null >::value();
  }
  static const char* value(const ::rfans_driver::nullResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RFANS_DRIVER_MESSAGE_NULL_H
