// Generated by gencpp from file rfans_driver/Point.msg
// DO NOT EDIT!


#ifndef RFANS_DRIVER_MESSAGE_POINT_H
#define RFANS_DRIVER_MESSAGE_POINT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace rfans_driver
{
template <class ContainerAllocator>
struct Point_
{
  typedef Point_<ContainerAllocator> Type;

  Point_()
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , a1(0.0)
    , a2(0.0)
    , a3(0.0)
    , a4(0.0)
    , b1(0.0)
    , b2(0.0)
    , b3(0.0)
    , b4(0.0)  {
    }
  Point_(const ContainerAllocator& _alloc)
    : x1(0.0)
    , y1(0.0)
    , x2(0.0)
    , y2(0.0)
    , a1(0.0)
    , a2(0.0)
    , a3(0.0)
    , a4(0.0)
    , b1(0.0)
    , b2(0.0)
    , b3(0.0)
    , b4(0.0)  {
  (void)_alloc;
    }



   typedef double _x1_type;
  _x1_type x1;

   typedef double _y1_type;
  _y1_type y1;

   typedef double _x2_type;
  _x2_type x2;

   typedef double _y2_type;
  _y2_type y2;

   typedef double _a1_type;
  _a1_type a1;

   typedef double _a2_type;
  _a2_type a2;

   typedef double _a3_type;
  _a3_type a3;

   typedef double _a4_type;
  _a4_type a4;

   typedef double _b1_type;
  _b1_type b1;

   typedef double _b2_type;
  _b2_type b2;

   typedef double _b3_type;
  _b3_type b3;

   typedef double _b4_type;
  _b4_type b4;





  typedef boost::shared_ptr< ::rfans_driver::Point_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::rfans_driver::Point_<ContainerAllocator> const> ConstPtr;

}; // struct Point_

typedef ::rfans_driver::Point_<std::allocator<void> > Point;

typedef boost::shared_ptr< ::rfans_driver::Point > PointPtr;
typedef boost::shared_ptr< ::rfans_driver::Point const> PointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::rfans_driver::Point_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::rfans_driver::Point_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace rfans_driver

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'rfans_driver': ['/home/mixiangdong/ceshi_ws/src/rfans_driver/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::rfans_driver::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::rfans_driver::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfans_driver::Point_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::rfans_driver::Point_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfans_driver::Point_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::rfans_driver::Point_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::rfans_driver::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c81b1cf288dd128754d09c9e4bbb83cf";
  }

  static const char* value(const ::rfans_driver::Point_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc81b1cf288dd1287ULL;
  static const uint64_t static_value2 = 0x54d09c9e4bbb83cfULL;
};

template<class ContainerAllocator>
struct DataType< ::rfans_driver::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "rfans_driver/Point";
  }

  static const char* value(const ::rfans_driver::Point_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::rfans_driver::Point_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#存储距离雷达最近的两对锥桶及其中心点的坐标\n\
\n\
float64 x1\n\
float64 y1\n\
float64 x2\n\
float64 y2\n\
float64 a1\n\
float64 a2\n\
float64 a3\n\
float64 a4\n\
float64 b1\n\
float64 b2\n\
float64 b3\n\
float64 b4\n\
\n\
\n\
\n\
\n\
\n\
\n\
";
  }

  static const char* value(const ::rfans_driver::Point_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::rfans_driver::Point_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x1);
      stream.next(m.y1);
      stream.next(m.x2);
      stream.next(m.y2);
      stream.next(m.a1);
      stream.next(m.a2);
      stream.next(m.a3);
      stream.next(m.a4);
      stream.next(m.b1);
      stream.next(m.b2);
      stream.next(m.b3);
      stream.next(m.b4);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Point_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::rfans_driver::Point_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::rfans_driver::Point_<ContainerAllocator>& v)
  {
    s << indent << "x1: ";
    Printer<double>::stream(s, indent + "  ", v.x1);
    s << indent << "y1: ";
    Printer<double>::stream(s, indent + "  ", v.y1);
    s << indent << "x2: ";
    Printer<double>::stream(s, indent + "  ", v.x2);
    s << indent << "y2: ";
    Printer<double>::stream(s, indent + "  ", v.y2);
    s << indent << "a1: ";
    Printer<double>::stream(s, indent + "  ", v.a1);
    s << indent << "a2: ";
    Printer<double>::stream(s, indent + "  ", v.a2);
    s << indent << "a3: ";
    Printer<double>::stream(s, indent + "  ", v.a3);
    s << indent << "a4: ";
    Printer<double>::stream(s, indent + "  ", v.a4);
    s << indent << "b1: ";
    Printer<double>::stream(s, indent + "  ", v.b1);
    s << indent << "b2: ";
    Printer<double>::stream(s, indent + "  ", v.b2);
    s << indent << "b3: ";
    Printer<double>::stream(s, indent + "  ", v.b3);
    s << indent << "b4: ";
    Printer<double>::stream(s, indent + "  ", v.b4);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RFANS_DRIVER_MESSAGE_POINT_H
