// Generated by gencpp from file rfans_driver/RfansCommand.msg
// DO NOT EDIT!


#ifndef RFANS_DRIVER_MESSAGE_RFANSCOMMAND_H
#define RFANS_DRIVER_MESSAGE_RFANSCOMMAND_H

#include <ros/service_traits.h>


#include <rfans_driver/RfansCommandRequest.h>
#include <rfans_driver/RfansCommandResponse.h>


namespace rfans_driver
{

struct RfansCommand
{

typedef RfansCommandRequest Request;
typedef RfansCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RfansCommand
} // namespace rfans_driver


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::rfans_driver::RfansCommand > {
  static const char* value()
  {
    return "2c14a5137ad0eede7d4a988cde7612e0";
  }

  static const char* value(const ::rfans_driver::RfansCommand&) { return value(); }
};

template<>
struct DataType< ::rfans_driver::RfansCommand > {
  static const char* value()
  {
    return "rfans_driver/RfansCommand";
  }

  static const char* value(const ::rfans_driver::RfansCommand&) { return value(); }
};


// service_traits::MD5Sum< ::rfans_driver::RfansCommandRequest> should match 
// service_traits::MD5Sum< ::rfans_driver::RfansCommand > 
template<>
struct MD5Sum< ::rfans_driver::RfansCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::rfans_driver::RfansCommand >::value();
  }
  static const char* value(const ::rfans_driver::RfansCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::rfans_driver::RfansCommandRequest> should match 
// service_traits::DataType< ::rfans_driver::RfansCommand > 
template<>
struct DataType< ::rfans_driver::RfansCommandRequest>
{
  static const char* value()
  {
    return DataType< ::rfans_driver::RfansCommand >::value();
  }
  static const char* value(const ::rfans_driver::RfansCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::rfans_driver::RfansCommandResponse> should match 
// service_traits::MD5Sum< ::rfans_driver::RfansCommand > 
template<>
struct MD5Sum< ::rfans_driver::RfansCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::rfans_driver::RfansCommand >::value();
  }
  static const char* value(const ::rfans_driver::RfansCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::rfans_driver::RfansCommandResponse> should match 
// service_traits::DataType< ::rfans_driver::RfansCommand > 
template<>
struct DataType< ::rfans_driver::RfansCommandResponse>
{
  static const char* value()
  {
    return DataType< ::rfans_driver::RfansCommand >::value();
  }
  static const char* value(const ::rfans_driver::RfansCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RFANS_DRIVER_MESSAGE_RFANSCOMMAND_H
